Assignments/Assignment 5/Assignment 5/Models/ErrorViewModel.cs
using System;

namespace Assignment_5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignments/Assignment 5/Assignment 5/Models/PotionsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment_5.Models
{
    public class PotionsModel
    {
        public string Name { get; set; }
    }
}

Assignments/Assignment 5/Assignment 5/Models/SpellsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment_5.Models
{
    public class SpellsModel
    {
        public string Name { get; set; }
    }
}

Assignments/Assignment 5/Assignment 5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Assignment_5.Models;

namespace Assignment_5.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Assignments/Assignment 5/Assignment 5/Controllers/PotionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment_5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;

namespace Assignment_5.Controllers
{
    public class PotionsController : Controller
    {
        public static PotionsDatabase potionsDatabase = new PotionsDatabase();
        // This will be replaced with dependency injection later on

        static PotionsController()
        {
            potionsDatabase.Add("ant");
            potionsDatabase.Add("bug");
            potionsDatabase.Add("Nirnroot");
            potionsDatabase.Add("Histcarp");
            potionsDatabase.Add("Honeycomb");
            potionsDatabase.Add("Deathbell");
            potionsDatabase.Add("Ectoplasm");
        }

        public IActionResult Index()
        {
            return View(potionsDatabase);
        }

        [HttpPost]
        public IActionResult AddIngredient()
        {
            if (Request.HasFormContentType)
            {
                if (Request.Form.Keys.Count == 2)
                {
                    if (Request.Form.TryGetValue(Request.Form.Keys.ElementAt(0), out StringValues first) &&
                    Request.Form.TryGetValue(Request.Form.Keys.ElementAt(1), out StringValues second))
                    {
                        potionsDatabase.Add(first.ToString(), second.ToString());
                    }
                }
                
            }
            return RedirectToAction("index");
        }
    }
}

Assignments/Assignment 5/Assignment 5/Controllers/SpellsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Assignment_5.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace Assignment_5.Controllers
{
    public class SpellsController : Controller
    {
        public static SpellsDatabase spellsDatabase = new SpellsDatabase();
        // This will be replaced with dependency injection later on

        static SpellsController()
        {
            spellsDatabase.Add("Sparks");
            spellsDatabase.Add("Flames");
            spellsDatabase.Add("Incinerate");
            spellsDatabase.Add("Transmogrify");
        }

        public IActionResult Index()
        {
            return View(spellsDatabase);
        }

        [HttpPost]
        public IActionResult Delete()
        {
            if (Request.HasFormContentType)
            {
                if (Request.Form.TryGetValue("spellIndex", out StringValues spellIndex))
                {
                    if (int.TryParse(spellIndex, out int index))
                    {
                        spellsDatabase.RemoveAt(index);
                    }
                }
            }
            return RedirectToAction("index");
        }

        [HttpPost]
        public IActionResult Add()
        {
            if (Request.HasFormContentType)
            {
                if (Request.Form.TryGetValue("spellName", out StringValues spellName))
                {
                    spellsDatabase.Add(spellName.ToString());
                }
            }
            return RedirectToAction("index");
        }

        public IActionResult ViewSpell(string id)
        {
            if (int.TryParse(id, out int result))
            {
                ViewData["id"] = id;
                return View(spellsDatabase.Get(result));
            }
            return RedirectToAction("index");
        }
    }
}

Assignments/Assignment 5/Assignment 5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Harry Potter";
}

<div class="text-center">
    <h1 class="display-4">You're a wizard Harry</h1>
    <p>Learn about <a href="https://www.wizardingworld.com">Harry Potter and the wizarding world.</a>.</p>
</div>

Assignments/Assignment 5/Assignment 5/Views/Potions/index.cshtml
<link rel="stylesheet" href="~/css/styles.css" />

@model PotionsDatabase

@{
    ViewData["Title"] = "Potions";
}

@if (Model.Any())
{
    <form method="post" action="potions/addIngredient">
        @for (var i = 0; i < Model.Count(); i++)
        {
            <div>
                <p class="list">@Model.Get(i).Name</p>
                <input type="checkbox" name=@Model.Get(i).Name value=@Model.Get(i).Name />
            </div>
        }
        <br />
        <input type="submit" value="Mix" />
    </form>
}
else
{
    <div>There are no spells to display</div>
}

Assignments/Assignment 5/Assignment 5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment_5</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment_5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spells" asp-action="Index">Spells</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Potions" asp-action="Index">Potions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Assignment_5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Assignments/Assignment 5/Assignment 5/Views/Spells/ViewSpell.cshtml
@model SpellsModel

@{
    ViewData["Title"] = Model.Name;
}


<h1>@Model.Name</h1>

<form method="post" action="/spells/delete">
    <input type="submit" value="Delete" />
    <input type="hidden" name="spellIndex" value="@ViewData["id"]" />
</form>

<form method="get" action="/">
    <input type="submit" value="Cancel" />
</form>

Assignments/Assignment 5/Assignment 5/Views/Spells/index.cshtml
<link rel="stylesheet" href="~/css/styles.css" />

@model SpellsDatabase

@{
    ViewData["Title"] = "Spells";
}

@if (Model.Any())
{
    <ol>
        @for (var i = 0; i < Model.Count(); i++)
        {
            @if (i % 2 != 0)
            {
                <li class="odd">@Model.Get(i).Name <a href="spells/viewSpell/@i">View Spell</a></li>
            }
            else
            {
                <li>@Model.Get(i).Name <a href="spells/viewSpell/@i">View Spell</a></li>
            }

        }
    </ol>

}
else
{
    <div>There are no spells to display</div>
}

<form method="post" action="spells/add">
    <input type="text" name="spellName" required="" />
    <input type="submit" value="Add" />
</form>